version: "3.9"

services:
  api:
    build: .
    container_name: btg-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=docker
      - MONGO_URI=mongodb://mongo:27017/btg-pactual-backend
      - JWT_SECRET=super-secret-key
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: btg-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:15
    container_name: btg-postgres
    environment:
      POSTGRES_USER: btg_user
      POSTGRES_PASSWORD: btg_password
      POSTGRES_DB: btg_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    

volumes:
  mongo_data:
  postgres_data:
